[package]
name = "udp-impl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
colog = "1.3.0"
colored = "3.0.0"
env_logger = "0.11.7"
log = "0.4.26"
rand = "0.9.0"
libc = "0.2.171"
